name: Generate SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install CycloneDX Node module
        run: npm install -g @cyclonedx/bom

      - name: Install dependencies
        run: npm install

      - name: Generate CycloneDX SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
