name: Generate SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install project dependencies
        run: npm install

      - name: Install CycloneDX SBOM tool
        run: npm install --save-dev @cyclonedx/npm

      - name: Generate SBOM
        run: npx @cyclonedx/npm --output-format json --output-file sbom.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
