name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CycloneDX CLI
        run: |
          curl -sL https://github.com/CycloneDX/cyclonedx-node-module/releases/latest/download/cyclonedx-npm-linux-x64 -o cyclonedx
          chmod +x cyclonedx
          sudo mv cyclonedx /usr/local/bin/

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx -o sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
